### PR TITLE
add cpf-cnpj mask to auto-detect if the document is a CPF or CNPJ

### PR DESCRIPTION
**Pull request by ronaldozanoni**
Add _cpf-cnpj_ mask to auto-detect if the document is a CPF or a CNPJ.

I needed it in an app and I think it could be helping more people.

### CODE REVIEW

**Comment by Aysion** [comment]
Hello, I would need this feature, but it looks like it was removed from the current commit.

**Comment by rodrigo98rm** [comment]
Awesome job @ronaldozanoni!
I'm trying to use this feature on version 1.13.0, but it's not working...
I get the following error: "Mask type not supported'.

There's also no mention of this feature on the README file.

**Comment by ronaldozanoni** [comment]
Hi @rodrigo98rm 
I was created in 2018, so I haven't tested with the repository changes.
I'll take a look at it this week... for now, you can try to use my fork https://github.com/ronaldozanoni/react-native-masked-text

**Comment by rodrigo98rm** [comment]
Thanks a lot @ronaldozanoni ! I will try it out.

**Pull request merged**
